// Generated by EmberScript 0.0.14
var CheckoutRegistrationRoute;
var get$ = Ember.get;
var set$ = Ember.set;
CheckoutRegistrationRoute = Ember.Route.extend({
  model: function () {
    return get$(get$(this, 'spree'), 'currentOrder');
  }
});
export default CheckoutRegistrationRoute;