// Generated by EmberScript 0.0.14
var AddressFormComponent;
var get$ = Ember.get;
import config from '../config/environment';
AddressFormComponent = Ember.Component.extend({
  address: null,
  addressKind: null,
  addressPrefix: Ember.computed(function () {
    return get$(this, 'addressKind').charAt(0);
  }).property('addressKind'),
  companyAddress: get$(get$(config, 'spreeConfig'), 'companyAddress'),
  alternativePhone: get$(get$(config, 'spreeConfig'), 'alternativePhone'),
  requiresState: get$(get$(config, 'spreeConfig'), 'requiresState'),
  requiresPhone: get$(get$(config, 'spreeConfig'), 'requiresPhone')
});
export default AddressFormComponent;