// Generated by EmberScript 0.0.14
var IndexRoute;
var get$ = Ember.get;
var set$ = Ember.set;
IndexRoute = Ember.Route.extend({
  model: function () {
    return Ember.RSVP.hash({ products: get$(this, 'store').find('product') });
  }
});
export default IndexRoute;