// Generated by EmberScript 0.0.14
var CheckoutAddressController;
var get$ = Ember.get;
var set$ = Ember.set;
CheckoutAddressController = Ember.Controller.extend({
  useBillingAsShipping: true,
  persistOrderAddress: false,
  showShippingForm: Ember.computed(function () {
    return !get$(this, 'useBillingAsShipping');
  }).property('useBillingAsShipping'),
  actions: {
    saveAndContinue: function () {
      set$(get$(this, 'model'), 'billAddress', get$(this, 'billAddress'));
      set$(get$(this, 'model'), 'shipAddress', get$(this, 'useBillingAsShipping') ? get$(this, 'billAddress') : get$(this, 'shipAddress'));
      return get$(this, 'model').save().then(function (this$) {
        return function (order) {
          debugger;
          return get$(this$, 'spree').advanceOrderState();
        };
      }(this), function (error) {
        debugger;
      });
    }
  }
});
export default CheckoutAddressController;