// Generated by EmberScript 0.0.14
var FlashMessage;
var get$ = Ember.get;
var set$ = Ember.set;
FlashMessage = Ember.Object.extend({
  timeout: null,
  type: null,
  message: null,
  isNagging: false,
  isNotice: Ember.computed(function () {
    return get$(this, 'type') === 'notice';
  }).property('type'),
  isWarning: Ember.computed(function () {
    return get$(this, 'type') === 'warning';
  }).property('type'),
  isError: Ember.computed(function () {
    return get$(this, 'type') === 'error';
  }).property('type')
});
export default FlashMessage;