// Generated by EmberScript 0.0.14
var Image;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Image = get$(DS, 'Model').extend({
  alt: DS.attr('string'),
  miniUrl: DS.attr('string'),
  smallUrl: DS.attr('string'),
  productUrl: DS.attr('string'),
  largeUrl: DS.attr('string')
});
export default Image;