// Generated by EmberScript 0.0.14
var LineItem;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
LineItem = get$(DS, 'Model').extend({
  variant: DS.belongsTo('variant'),
  quantity: DS.attr('number'),
  singleDisplayAmount: DS.attr('string', { readOnly: true }),
  insufficientStock: DS.attr('boolean', { readOnly: true }),
  price: DS.attr('number'),
  total: DS.attr('number')
});
export default LineItem;