// Generated by EmberScript 0.0.14
var Product;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Product = get$(DS, 'Model').extend({
  name: DS.attr('string'),
  description: DS.attr('string'),
  price: DS.attr('number'),
  displayPrice: DS.attr('string'),
  slug: DS.attr('string'),
  images: DS.hasMany('image'),
  variantsIncludingMaster: DS.hasMany('variant'),
  productProperties: DS.hasMany('productProperty')
});
export default Product;