// Generated by EmberScript 0.0.14
var ShippingRate;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
ShippingRate = get$(DS, 'Model').extend({
  name: DS.attr('string'),
  cost: DS.attr('number'),
  selected: DS.attr('boolean'),
  displayCost: DS.attr('string'),
  shippingMethod: DS.belongsTo('shippingMethod')
});
export default ShippingRate;