// Generated by EmberScript 0.0.14
var Shipment;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Shipment = get$(DS, 'Model').extend({
  tracking: DS.attr('string'),
  number: DS.attr('string'),
  cost: DS.attr('number'),
  shippedAt: DS.attr('date'),
  state: DS.attr('string'),
  order: DS.belongsTo('order'),
  stockLocation: DS.belongsTo('stockLocation'),
  shippingRates: DS.hasMany('shippingRate')
});
export default Shipment;