// Generated by EmberScript 0.0.14
var ApplicationAdapter, ApplicationAdapter;
var get$ = Ember.get;
import DS from 'ember-data';
import config from '../config/environment';
if (get$(config, 'environment') === 'test') {
  ApplicationAdapter = get$(DS, 'ActiveModelAdapter').extend({ namespace: 'api/ams' });
} else {
  ApplicationAdapter = get$(DS, 'ActiveModelAdapter').extend({
    namespace: 'api/ams',
    host: get$(get$(config, 'spreeConfig'), 'apiHost'),
    headers: Ember.computed(function () {
      if (get$(get$(this, 'spree'), 'guestToken') && get$(get$(this, 'spree'), 'orderId'))
        return {
          'X-Spree-Order-Token': get$(get$(this, 'spree'), 'guestToken'),
          'X-Spree-Order-Id': get$(get$(this, 'spree'), 'orderId')
        };
    }).property('spree.guestToken', 'spree.orderId')
  });
}
export default ApplicationAdapter;