// Generated by EmberScript 0.0.14
var Initializer;
var get$ = Ember.get;
var set$ = Ember.set;
import Session from 'simple-auth/session';
import Devise from 'simple-auth-devise/authorizers/devise';
Initializer = {
  name: 'customize-simple-auth',
  before: 'simple-auth',
  initialize: function (container, application) {
    Devise.reopen({
      authorize: function (jqXHR, requestOptions) {
        get$(this, '_super').apply(this, arguments);
        return jqXHR.setRequestHeader('X-Spree-Token', get$(get$(this, 'session'), 'user_token'));
      }
    });
    return Session.reopen({
      currentUser: Ember.computed(function () {
        var userId;
        if (userId = get$(this, 'user_id'))
          return get$(this, 'container').lookup('store:main').find('user', userId);
      }).property('user_id')
    });
  }
};
export default Initializer;