// Generated by EmberScript 0.0.14
var Initializer;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Initializer = {
  name: 'find-by-slug',
  initialize: function (container, application) {
    return get$(DS, 'Store').reopen({
      findBySlug: function (type, slug, preload) {
        var adapter, promise, serializer, store;
        Ember.assert("You need to pass a type to the store's findBySlug method", get$(arguments, 'length') >= 1);
        Ember.assert("You need to pass a slug to the store's findBySlug method", get$(arguments, 'length') >= 2);
        store = this;
        type = this.modelFor(type);
        adapter = this.adapterFor(type);
        serializer = this.serializerFor(type);
        promise = adapter.find(store, type, slug, null);
        return promise.then(function (adapterPayload) {
          var payload;
          payload = serializer.extract(store, type, adapterPayload, slug, 'find');
          return store.push(type, payload);
        }, function (error) {
          throw error;
        });
      }
    });
  }
};
export default Initializer;