// Generated by EmberScript 0.0.14
var Address;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Address = get$(DS, 'Model').extend({
  firstname: DS.attr('string'),
  lastname: DS.attr('string'),
  address1: DS.attr('string'),
  address2: DS.attr('string'),
  city: DS.attr('string'),
  zipcode: DS.attr('string'),
  phone: DS.attr('string'),
  stateName: DS.attr('string'),
  alternativePhone: DS.attr('string'),
  company: DS.attr('string'),
  state: DS.belongsTo('state'),
  country: DS.belongsTo('country')
});
export default Address;