// Generated by EmberScript 0.0.14
var FlashQueue;
var get$ = Ember.get;
var set$ = Ember.set;
import FlashMessage from "../models/flash-message";
FlashQueue = Ember.ArrayController.extend({
  queueName: null,
  timer: null,
  defaultType: 'notice',
  defaultTimeout: 4e3,
  pushFlash: function (message, params) {
    if (null != params)
      params;
    else
      params = {};
    return this.pushObject(FlashMessage.create({
      message: message,
      type: null != get$(params, 'type') ? get$(params, 'type') : get$(this, 'defaultType'),
      isNagging: null != get$(params, 'isNagging') ? get$(params, 'isNagging') : false,
      flashTimeout: null != get$(params, 'flashTimeout') ? get$(params, 'flashTimeout') : get$(this, 'defaultTimeout')
    }));
  },
  dismissFlash: function () {
    if (get$(this, 'timer'))
      Ember.run.cancel(get$(this, 'timer'));
    set$(this, 'timer', null);
    return this.removeObject(this.objectAt(0));
  },
  contentChanged: Ember.observer(function () {
    var currentMessage;
    if (!(get$(this, 'timer') || Ember.empty(get$(this, 'content')))) {
      currentMessage = this.objectAt(0);
      if (!get$(currentMessage, 'isNagging'))
        return set$(this, 'timer', Ember.run.later(this, get$(this, 'dismissFlash'), get$(currentMessage, 'flashTimeout')));
    }
  }, 'content.[]')
});
export default FlashQueue;