// Generated by EmberScript 0.0.14
var Order;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Order = get$(DS, 'Model').extend({
  additionalTaxTotal: DS.attr('number', { readOnly: true }),
  adjustmentTotal: DS.attr('number', { readOnly: true }),
  channel: DS.attr('string', { readOnly: true }),
  checkoutSteps: DS.attr('array', { readOnly: true }),
  completedAt: DS.attr('date', { readOnly: true }),
  confirmationDelivered: DS.attr('boolean'),
  consideredRisky: DS.attr('boolean', { readOnly: true }),
  createdAt: DS.attr('date', { readOnly: true }),
  currency: DS.attr('string', { readOnly: true }),
  email: DS.attr('string'),
  guestToken: DS.attr('string', { readOnly: true }),
  includedTaxTotal: DS.attr('number', { readOnly: true }),
  itemCount: DS.attr('number', { readOnly: true }),
  itemTotal: DS.attr('number', { readOnly: true }),
  number: DS.attr('string', { readOnly: true }),
  paymentTotal: DS.attr('number', { readOnly: true }),
  promoTotal: DS.attr('number', { readOnly: true }),
  shipmentTotal: DS.attr('number', { readOnly: true }),
  specialInstructions: DS.attr('string'),
  state: DS.attr('string', { readOnly: true }),
  total: DS.attr('number', { readOnly: true }),
  updatedAt: DS.attr('date', { readOnly: true }),
  billAddress: DS.belongsTo('address'),
  shipAddress: DS.belongsTo('address'),
  lineItems: DS.hasMany('lineItem'),
  shipments: DS.hasMany('shipment'),
  shippingMethod: DS.belongsTo('shippingMethod'),
  empty: Ember.computed(function () {
    return get$(this, 'itemCount') === 0;
  }).property('itemCount'),
  hasEmail: Ember.computed(function () {
    if (get$(this, 'email'))
      return get$(get$(this, 'email'), 'length') > 0;
  }).property('email'),
  notConfirm: Ember.computed(function () {
    return get$(this, 'state') === !'confirm';
  }).property('state')
});
export default Order;