// Generated by EmberScript 0.0.14
var ShippingCategory;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
ShippingCategory = get$(DS, 'Model').extend({ name: DS.attr('string') });
export default ShippingCategory;