// Generated by EmberScript 0.0.14
var ShippingMethod;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
ShippingMethod = get$(DS, 'Model').extend({
  name: DS.attr('string'),
  zones: DS.hasMany('zone'),
  shippingCategories: DS.hasMany('shippingCategory')
});
export default ShippingMethod;