// Generated by EmberScript 0.0.14
var State;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
State = get$(DS, 'Model').extend({
  name: DS.attr('string'),
  abbr: DS.attr('string'),
  country: DS.belongsTo('country')
});
export default State;