// Generated by EmberScript 0.0.14
var Zone;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
Zone = get$(DS, 'Model').extend({
  name: DS.attr('string'),
  description: DS.attr('string')
});
export default Zone;