// Generated by EmberScript 0.0.14
var ApplicationRoute;
var get$ = Ember.get;
var set$ = Ember.set;
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';
ApplicationRoute = Ember.Route.extend(ApplicationRouteMixin, {
  init: function () {
    get$(this, 'spree').on('spreeOrderDidAdvance', function (this$) {
      return function () {
        return this$.transitionTo('checkout');
      };
    }(this));
    get$(this, 'spree').on('spreeOrderDidNotAdvance', function (this$) {
      return function (error) {
        switch (get$(error, 'statusText')) {
        case 'Not Found':
          get$(this$, 'flash').pushFlash('Order could not be found in the backend.', { type: 'error' });
          set$(get$(this$, 'spree'), 'currentOrder', null);
          return this$.transitionTo('index');
        default: {
            debugger;
            return get$(this$, 'flash').pushFlash('Order could not transition.', { type: 'error' });
          }
        }
      };
    }(this));
    return get$(this, 'spree').on('spreeOrderCanNotAdvance', function (this$) {
      return function () {
        return this$.transitionTo('checkout');
      };
    }(this));
  },
  actions: {
    sessionAuthenticationFailed: function (error) {
      return get$(this, 'flash').pushFlash('Invalid email or password.', {
        type: 'error',
        isNagging: true
      });
    }
  }
});
export default ApplicationRoute;