// Generated by EmberScript 0.0.14
var CheckoutAddressRoute;
var get$ = Ember.get;
var set$ = Ember.set;
CheckoutAddressRoute = Ember.Route.extend({
  setupController: function (controller, model) {
    this._super(controller, model);
    set$(controller, 'billAddress', get$(model, 'billAddress') || get$(this, 'store').createRecord('address'));
    set$(controller, 'shipAddress', get$(model, 'shipAddress') || get$(this, 'store').createRecord('address'));
    return set$(controller, 'countries', get$(this, 'store').find('country'));
  }
});
export default CheckoutAddressRoute;