// Generated by EmberScript 0.0.14
var CheckoutRegistrationController;
var get$ = Ember.get;
var set$ = Ember.set;
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';
CheckoutRegistrationController = Ember.Controller.extend(LoginControllerMixin, {
  authenticator: 'simple-auth-authenticator:devise',
  actions: {
    continueAsGuest: function () {
      set$(get$(get$(this, 'spree'), 'currentOrder'), 'email', get$(this, 'guestEmail'));
      return get$(this, 'spree').saveCurrentOrder();
    }
  }
});
export default CheckoutRegistrationController;