// Generated by EmberScript 0.0.14
var UsersShowRoute;
var get$ = Ember.get;
var set$ = Ember.set;
import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin';;
UsersShowRoute = Ember.Route.extend(AuthenticatedRouteMixin);
export default UsersShowRoute;;