// Generated by EmberScript 0.0.14
var ApplicationSerializer;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from 'ember-data';
import ReadOnly from '../mixins/read-only';
ApplicationSerializer = get$(DS, 'ActiveModelSerializer').extend(ReadOnly);
export default ApplicationSerializer;