// Generated by EmberScript 0.0.14
var OrderSerializer;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from 'ember-data';
import ApplicationSerializer from './application';
OrderSerializer = ApplicationSerializer.extend(get$(DS, 'EmbeddedRecordsMixin'), {
  attrs: {
    billAddress: {
      serialize: 'records',
      deserialize: 'id'
    },
    shipAddress: {
      serialize: 'records',
      deserialize: 'id'
    }
  }
});
export default OrderSerializer;