// Generated by EmberScript 0.0.14
var ArrayTransform;
var get$ = Ember.get;
var set$ = Ember.set;
import DS from "ember-data";
ArrayTransform = get$(DS, 'Transform').extend({
  deserialize: function (serialized) {
    if (Ember.isArray(serialized)) {
      return Ember.A(serialized);
    } else {
      return Ember.A;
    }
  },
  serialize: function (deserialized) {
    if (Ember.isArray(deserialized)) {
      return Ember.A(deserialized);
    } else {
      return Ember.A;
    }
  }
});
export default ArrayTransform;