// Generated by EmberScript 0.0.14
var FlashController;
var get$ = Ember.get;
var set$ = Ember.set;
import FlashQueue from "../models/flash-queue";
FlashController = Ember.Controller.extend({
  queues: [],
  defaultQueueName: 'main',
  init: function () {
    return this.findOrCreateQueue(get$(this, 'defaultQueueName'));
  },
  findOrCreateQueue: function (queueName) {
    var queue;
    if (queue = get$(this, 'queues').findBy('queueName', queueName)) {
      return queue;
    } else {
      return get$(this, 'queues').pushObject(FlashQueue.create({ queueName: queueName }));
    }
  },
  pushFlash: function (message, options) {
    var queue, queueName;
    if (null != options)
      options;
    else
      options = {};
    queueName = get$(options, 'queueName') ? get$(options, 'queueName') : get$(this, 'defaultQueueName');
    queue = this.findOrCreateQueue(queueName);
    return queue.pushFlash(message, options);
  }
});
export default FlashController;