// Generated by EmberScript 0.0.14
var UsersLoginController;
var get$ = Ember.get;
var set$ = Ember.set;
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';
UsersLoginController = Ember.Controller.extend(LoginControllerMixin, { authenticator: 'simple-auth-authenticator:devise' });
export default UsersLoginController;