// Generated by EmberScript 0.0.14
var UsersNewontroller;
var get$ = Ember.get;
var set$ = Ember.set;
UsersNewontroller = Ember.Controller.extend({
  actions: {
    createUser: function () {
      var password;
      password = get$(get$(this, 'model'), 'password');
      return get$(this, 'model').save().then(function (this$) {
        return function (user) {
          return get$(this$, 'session').authenticate('simple-auth-authenticator:devise', {
            identification: get$(user, 'email'),
            password: password
          }).then(function () {
            return console.log('user created and authenticated');
          }, function () {
            return console.log('user created but NOT authenticated');
          });
        };
      }(this), function (error) {
        debugger;
        return console.log('failz');
      });
    }
  }
});
export default UsersNewontroller;