// Generated by EmberScript 0.0.14
var UsersNewRoute;
var get$ = Ember.get;
var set$ = Ember.set;
UsersNewRoute = Ember.Route.extend({
  model: function () {
    return get$(this, 'store').createRecord('user');
  }
});
export default UsersNewRoute;;