// Generated by EmberScript 0.0.14
var ProductsShowRoute;
var get$ = Ember.get;
var set$ = Ember.set;
ProductsShowRoute = Ember.Route.extend({
  model: function (params) {
    return get$(this, 'store').findBySlug('product', get$(params, 'slug'));
  }
});
export default ProductsShowRoute;;