// Generated by EmberScript 0.0.14
var spreeHost;
var get$ = Ember.get;
var set$ = Ember.set;
import config from '../config/environment';
spreeHost = Ember.Handlebars.makeBoundHelper(function (path) {
  return '' + get$(get$(config, 'spreeConfig'), 'apiHost') + path;
});
export default spreeHost;